[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[window]
padding = { x = 4, y = 2 }
opacity = 0.75
blur = true
startup_mode = "Fullscreen"

[scrolling]
history = 100000
multiplier = 5

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
size = 12.0
offset = { x = 0, y = 4 }

[terminal]
shell = { program = "/bin/zsh", args = ["-l", "-c", "tmux"] }

[[keyboard.bindings]]
key = "Tab"
mods = "Control"
chars = "\u001b[9;5u"

[[keyboard.bindings]]
key = "Tab"
mods = "Control|Shift"
chars = "\u001b[9;6u"

[[keyboard.bindings]]
key = "Enter"
mods = "Command"
chars = "\u001b[13;3u"

[[keyboard.bindings]]
key = "/"
mods = "Command"
chars = "\u001b[47;3u"

[[keyboard.bindings]]
key = "a"
mods = "Command"
chars = "\u001b[97;3u"

[[keyboard.bindings]]
key = "b"
mods = "Command"
chars = "\u001b[98;3u"

[[keyboard.bindings]]
key = "e"
mods = "Command|Shift"
chars = "\u001b[101;4u"

[[keyboard.bindings]]
key = "f"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "f"
mods = "Command|Shift"
chars = "\u001b[102;4u"

[[keyboard.bindings]]
key = "h"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "h"
mods = "Command|Shift"
chars = "\u001b[104;4u"

[[keyboard.bindings]]
key = "j"
mods = "Command"
chars = "\u001b[106;3u"

[[keyboard.bindings]]
key = "k"
mods = "Command"
chars = "\u001b[107;3u"

[[keyboard.bindings]]
key = "n"
mods = "Command"
chars = "\u001b[110;3u"

[[keyboard.bindings]]
key = "n"
mods = "Command|Shift"
chars = "\u001b[110;4u"

[[keyboard.bindings]]
key = "p"
mods = "Command"
chars = "\u001b[112;3u"

[[keyboard.bindings]]
key = "p"
mods = "Command|Shift"
chars = "\u001b[112;4u"

[[keyboard.bindings]]
key = "q"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "s"
mods = "Command"
chars = "\u001b[115;3u"

[[keyboard.bindings]]
key = "t"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "w"
mods = "Command"
chars = "\u001b[119;3u"

